version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:8080
      - 53530:53530
    environment:
      - HTTP_PORT=8080
      - DNS_PORT=53530
      - DB_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file: .env
    depends_on:
      - "db"
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  db-store:

